-- Route API schema stabilization for prod/dev PostgreSQL.
-- Run with: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/db/migrations/2026-05-10_route_api_schema.sql

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS route_sessions (
    session_id uuid PRIMARY KEY,
    user_id uuid NOT NULL,
    route_id varchar(120) NOT NULL,
    active_route_key varchar(120),
    start_point geometry(Point, 4326) NOT NULL,
    end_point geometry(Point, 4326) NOT NULL,
    route_snapshot_json jsonb NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS session_id uuid;
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS route_id varchar(120);
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS active_route_key varchar(120);
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS start_point geometry(Point, 4326);
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS end_point geometry(Point, 4326);
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS route_snapshot_json jsonb;
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS status varchar(30) DEFAULT 'ACTIVE';
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE route_sessions ADD COLUMN IF NOT EXISTS updated_at timestamp(6) DEFAULT CURRENT_TIMESTAMP;

UPDATE route_sessions
SET active_route_key = route_id
WHERE status = 'ACTIVE'
  AND active_route_key IS NULL
  AND route_id IS NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM route_sessions
        WHERE user_id IS NULL
           OR route_id IS NULL
           OR session_id IS NULL
           OR start_point IS NULL
           OR end_point IS NULL
           OR route_snapshot_json IS NULL
           OR status IS NULL
           OR created_at IS NULL
           OR updated_at IS NULL
    ) THEN
        RAISE EXCEPTION 'route_sessions contains NULL values required by RouteSession entity';
    END IF;
END $$;

ALTER TABLE route_sessions ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN session_id SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN route_id SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN start_point SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN end_point SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN route_snapshot_json SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN status SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE route_sessions ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'route_sessions'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE route_sessions
            ADD CONSTRAINT route_sessions_pkey
            PRIMARY KEY (session_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_route_sessions_user'
    ) THEN
        ALTER TABLE route_sessions
            ADD CONSTRAINT fk_route_sessions_user
            FOREIGN KEY (user_id)
            REFERENCES users(user_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_route_sessions_user_active_route'
    ) THEN
        ALTER TABLE route_sessions
            ADD CONSTRAINT uk_route_sessions_user_active_route
            UNIQUE (user_id, active_route_key);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_route_sessions_user_route_updated
    ON route_sessions (user_id, route_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_route_sessions_route_updated
    ON route_sessions (route_id, updated_at);

CREATE TABLE IF NOT EXISTS route_ratings (
    rating_id bigserial PRIMARY KEY,
    user_id uuid NOT NULL,
    session_id uuid NOT NULL,
    route_id varchar(120) NOT NULL,
    score smallint NOT NULL,
    route_context_json jsonb NOT NULL,
    created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS rating_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS session_id uuid;
ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS route_id varchar(120);
ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS score smallint;
ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS route_context_json jsonb;
ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE route_ratings ADD COLUMN IF NOT EXISTS updated_at timestamp(6) DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM route_ratings
        WHERE user_id IS NULL
           OR rating_id IS NULL
           OR session_id IS NULL
           OR route_id IS NULL
           OR score IS NULL
           OR route_context_json IS NULL
           OR created_at IS NULL
           OR updated_at IS NULL
    ) THEN
        RAISE EXCEPTION 'route_ratings contains NULL values required by RouteRating entity';
    END IF;
END $$;

ALTER TABLE route_ratings ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE route_ratings ALTER COLUMN rating_id SET NOT NULL;
ALTER TABLE route_ratings ALTER COLUMN session_id SET NOT NULL;
ALTER TABLE route_ratings ALTER COLUMN route_id SET NOT NULL;
ALTER TABLE route_ratings ALTER COLUMN score SET NOT NULL;
ALTER TABLE route_ratings ALTER COLUMN route_context_json SET NOT NULL;
ALTER TABLE route_ratings ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE route_ratings ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'route_ratings'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE route_ratings
            ADD CONSTRAINT route_ratings_pkey
            PRIMARY KEY (rating_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_route_ratings_user'
    ) THEN
        ALTER TABLE route_ratings
            ADD CONSTRAINT fk_route_ratings_user
            FOREIGN KEY (user_id)
            REFERENCES users(user_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_route_ratings_session'
    ) THEN
        ALTER TABLE route_ratings
            ADD CONSTRAINT fk_route_ratings_session
            FOREIGN KEY (session_id)
            REFERENCES route_sessions(session_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_route_ratings_score_range'
    ) THEN
        ALTER TABLE route_ratings
            ADD CONSTRAINT ck_route_ratings_score_range
            CHECK (score BETWEEN 1 AND 5);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_route_ratings_session'
    ) THEN
        ALTER TABLE route_ratings
            ADD CONSTRAINT uk_route_ratings_session
            UNIQUE (session_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS subway_stations (
    subway_station_id bigserial PRIMARY KEY,
    odsay_station_id varchar(30) NOT NULL,
    station_name varchar(100) NOT NULL,
    line_name varchar(50) NOT NULL,
    point geometry(Point, 4326)
);

ALTER TABLE subway_stations ADD COLUMN IF NOT EXISTS odsay_station_id varchar(30);
ALTER TABLE subway_stations ADD COLUMN IF NOT EXISTS subway_station_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE subway_stations ADD COLUMN IF NOT EXISTS station_name varchar(100);
ALTER TABLE subway_stations ADD COLUMN IF NOT EXISTS line_name varchar(50);
ALTER TABLE subway_stations ADD COLUMN IF NOT EXISTS point geometry(Point, 4326);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM subway_stations
        WHERE odsay_station_id IS NULL
           OR subway_station_id IS NULL
           OR station_name IS NULL
           OR line_name IS NULL
    ) THEN
        RAISE EXCEPTION 'subway_stations contains NULL values required by SubwayStation entity';
    END IF;
END $$;

ALTER TABLE subway_stations ALTER COLUMN odsay_station_id SET NOT NULL;
ALTER TABLE subway_stations ALTER COLUMN subway_station_id SET NOT NULL;
ALTER TABLE subway_stations ALTER COLUMN station_name SET NOT NULL;
ALTER TABLE subway_stations ALTER COLUMN line_name SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'subway_stations'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE subway_stations
            ADD CONSTRAINT subway_stations_pkey
            PRIMARY KEY (subway_station_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_subway_stations_odsay_station_id'
    ) THEN
        ALTER TABLE subway_stations
            ADD CONSTRAINT uk_subway_stations_odsay_station_id
            UNIQUE (odsay_station_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_subway_stations_station_line
    ON subway_stations (station_name, line_name);

CREATE TABLE IF NOT EXISTS subway_timetables (
    subway_timetable_id bigserial PRIMARY KEY,
    odsay_station_id varchar(30) NOT NULL,
    service_day_type varchar(30) NOT NULL,
    way_code integer NOT NULL,
    departure_time_text varchar(10) NOT NULL,
    departure_second_of_day integer NOT NULL,
    end_station_name varchar(100) NOT NULL
);

ALTER TABLE subway_timetables ADD COLUMN IF NOT EXISTS odsay_station_id varchar(30);
ALTER TABLE subway_timetables ADD COLUMN IF NOT EXISTS subway_timetable_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE subway_timetables ADD COLUMN IF NOT EXISTS service_day_type varchar(30);
ALTER TABLE subway_timetables ADD COLUMN IF NOT EXISTS way_code integer;
ALTER TABLE subway_timetables ADD COLUMN IF NOT EXISTS departure_time_text varchar(10);
ALTER TABLE subway_timetables ADD COLUMN IF NOT EXISTS departure_second_of_day integer;
ALTER TABLE subway_timetables ADD COLUMN IF NOT EXISTS end_station_name varchar(100);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM subway_timetables
        WHERE odsay_station_id IS NULL
           OR subway_timetable_id IS NULL
           OR service_day_type IS NULL
           OR way_code IS NULL
           OR departure_time_text IS NULL
           OR departure_second_of_day IS NULL
           OR end_station_name IS NULL
    ) THEN
        RAISE EXCEPTION 'subway_timetables contains NULL values required by SubwayTimetable entity';
    END IF;
END $$;

ALTER TABLE subway_timetables ALTER COLUMN odsay_station_id SET NOT NULL;
ALTER TABLE subway_timetables ALTER COLUMN subway_timetable_id SET NOT NULL;
ALTER TABLE subway_timetables ALTER COLUMN service_day_type SET NOT NULL;
ALTER TABLE subway_timetables ALTER COLUMN way_code SET NOT NULL;
ALTER TABLE subway_timetables ALTER COLUMN departure_time_text SET NOT NULL;
ALTER TABLE subway_timetables ALTER COLUMN departure_second_of_day SET NOT NULL;
ALTER TABLE subway_timetables ALTER COLUMN end_station_name SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'subway_timetables'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE subway_timetables
            ADD CONSTRAINT subway_timetables_pkey
            PRIMARY KEY (subway_timetable_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_subway_timetables_service_day_type'
    ) THEN
        ALTER TABLE subway_timetables
            ADD CONSTRAINT ck_subway_timetables_service_day_type
            CHECK (service_day_type IN ('WEEKDAY', 'SATURDAY', 'HOLIDAY'));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_subway_timetables_lookup'
    ) THEN
        ALTER TABLE subway_timetables
            ADD CONSTRAINT uk_subway_timetables_lookup
            UNIQUE (
                odsay_station_id,
                service_day_type,
                way_code,
                departure_second_of_day,
                end_station_name
            );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_stt_next_dep
    ON subway_timetables (odsay_station_id, service_day_type, way_code, departure_second_of_day);

COMMIT;

SELECT 'route_sessions' AS table_name, COUNT(*) AS row_count FROM route_sessions
UNION ALL
SELECT 'route_ratings', COUNT(*) FROM route_ratings
UNION ALL
SELECT 'subway_stations', COUNT(*) FROM subway_stations
UNION ALL
SELECT 'subway_timetables', COUNT(*) FROM subway_timetables;
