-- Source feature schema for persistent CSV accessibility source data.
-- Run with: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/db/migrations/2026-05-10_source_features_schema.sql

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS source_features (
    source_feature_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_type varchar(50) NOT NULL,
    geom geometry(Geometry, 4326) NOT NULL,
    state varchar(50),
    value_number numeric(10, 2),
    source_file varchar(255) NOT NULL
);

ALTER TABLE source_features ADD COLUMN IF NOT EXISTS source_feature_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE source_features ADD COLUMN IF NOT EXISTS feature_type varchar(50);
ALTER TABLE source_features ADD COLUMN IF NOT EXISTS geom geometry(Geometry, 4326);
ALTER TABLE source_features ADD COLUMN IF NOT EXISTS state varchar(50);
ALTER TABLE source_features ADD COLUMN IF NOT EXISTS value_number numeric(10, 2);
ALTER TABLE source_features ADD COLUMN IF NOT EXISTS source_file varchar(255);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM source_features
        WHERE source_feature_id IS NULL
           OR feature_type IS NULL
           OR geom IS NULL
           OR source_file IS NULL
    ) THEN
        RAISE EXCEPTION 'source_features contains NULL values required by SourceFeature entity';
    END IF;
END $$;

ALTER TABLE source_features ALTER COLUMN source_feature_id SET NOT NULL;
ALTER TABLE source_features ALTER COLUMN feature_type SET NOT NULL;
ALTER TABLE source_features ALTER COLUMN geom SET NOT NULL;
ALTER TABLE source_features ALTER COLUMN source_file SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'source_features'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE source_features
            ADD CONSTRAINT source_features_pkey
            PRIMARY KEY (source_feature_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_source_features_geom
    ON source_features
    USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_source_features_type_file
    ON source_features (feature_type, source_file);

COMMIT;

SELECT 'source_features' AS table_name, COUNT(*) AS row_count FROM source_features;
