CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS bus_stops (
    bus_stop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bstop_id VARCHAR(30) NOT NULL,
    stop_name VARCHAR(100) NOT NULL,
    ars_no VARCHAR(20),
    stop_type VARCHAR(30),
    point geometry(Point, 4326) NOT NULL,
    active BOOLEAN NOT NULL,
    synced_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_bus_stops_bstop_id ON bus_stops (bstop_id);
CREATE INDEX IF NOT EXISTS idx_bus_stops_active ON bus_stops (active);
CREATE INDEX IF NOT EXISTS idx_bus_stops_stop_name ON bus_stops (stop_name);
CREATE INDEX IF NOT EXISTS idx_bus_stops_ars_no ON bus_stops (ars_no);

CREATE TABLE IF NOT EXISTS subway_station_accessibility_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subway_station_id BIGINT NOT NULL,
    feature_type VARCHAR(50) NOT NULL,
    is_available BOOLEAN NOT NULL,
    CONSTRAINT fk_subway_station_accessibility_features_station
        FOREIGN KEY (subway_station_id)
        REFERENCES subway_stations (subway_station_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_subway_station_accessibility_features_station_type
    ON subway_station_accessibility_features (subway_station_id, feature_type);
CREATE INDEX IF NOT EXISTS idx_subway_station_accessibility_features_station
    ON subway_station_accessibility_features (subway_station_id);

ALTER TABLE IF EXISTS bookmarks
    ALTER COLUMN place_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    log_id BIGSERIAL PRIMARY KEY,
    actor_user_id UUID,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id VARCHAR(120),
    gu VARCHAR(40),
    dong VARCHAR(80),
    summary TEXT NOT NULL,
    before_json JSONB,
    after_json JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_log_id
    ON admin_audit_logs (log_id DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_filter
    ON admin_audit_logs (action, gu, dong, actor_user_id, log_id DESC);

CREATE TABLE IF NOT EXISTS routing_segment_overrides (
    edge_id BIGINT PRIMARY KEY,
    walk_access VARCHAR(30),
    stairs_state VARCHAR(30),
    width_state VARCHAR(30),
    braille_block_state VARCHAR(30),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_routing_segment_overrides_edge_id
        FOREIGN KEY (edge_id)
        REFERENCES road_segments (edge_id)
        ON DELETE CASCADE
);

ALTER TABLE routing_segment_overrides
    ALTER COLUMN walk_access DROP NOT NULL;

ALTER TABLE routing_segment_overrides
    ADD COLUMN IF NOT EXISTS stairs_state VARCHAR(30);

ALTER TABLE routing_segment_overrides
    ADD COLUMN IF NOT EXISTS width_state VARCHAR(30);

ALTER TABLE routing_segment_overrides
    ADD COLUMN IF NOT EXISTS braille_block_state VARCHAR(30);

ALTER TABLE routing_segment_overrides
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE road_segments
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_road_segments_geom_gist
    ON road_segments
    USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_admin_areas_geom_gist
    ON admin_areas
    USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_segment_features_edge_id
    ON segment_features (edge_id);

CREATE TABLE IF NOT EXISTS routing_apply_states (
    state_key VARCHAR(60) PRIMARY KEY,
    dirty BOOLEAN NOT NULL DEFAULT FALSE,
    applying BOOLEAN NOT NULL DEFAULT FALSE,
    applying_started_at TIMESTAMP,
    dirty_marked_at TIMESTAMP,
    last_applied_at TIMESTAMP,
    last_result_status VARCHAR(30),
    last_result_message TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO routing_apply_states (
    state_key,
    dirty,
    applying,
    applying_started_at,
    last_result_status,
    last_result_message,
    updated_at
) VALUES (
    'ROUTING_OVERRIDES',
    FALSE,
    FALSE,
    NULL,
    'SKIPPED',
    '아직 반영할 경로 변경이 없습니다.',
    CURRENT_TIMESTAMP
)
ON CONFLICT (state_key) DO NOTHING;

ALTER TABLE IF EXISTS hazard_reports
    ADD COLUMN IF NOT EXISTS processed_by_user_id UUID;

ALTER TABLE IF EXISTS hazard_reports
    ADD COLUMN IF NOT EXISTS processed_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_hazard_reports_status
    ON hazard_reports (status);

CREATE INDEX IF NOT EXISTS idx_hazard_reports_report_point_gist
    ON hazard_reports
    USING GIST (report_point);

CREATE TABLE IF NOT EXISTS hazard_report_route_reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    intent VARCHAR(30) NOT NULL,
    stage VARCHAR(30) NOT NULL,
    reviewer_user_id UUID NOT NULL,
    gu VARCHAR(40) NOT NULL,
    dong VARCHAR(80) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    routing_apply_status VARCHAR(30),
    routing_apply_message TEXT,
    routing_applied_at TIMESTAMP,
    selected_segment_edge_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hazard_report_route_reviews_report_id
        FOREIGN KEY (report_id)
        REFERENCES hazard_reports (report_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_hazard_report_route_reviews_in_progress
    ON hazard_report_route_reviews (report_id)
    WHERE stage = 'IN_PROGRESS';

CREATE INDEX IF NOT EXISTS idx_hazard_report_route_reviews_report_id
    ON hazard_report_route_reviews (report_id, review_id DESC);

ALTER TABLE IF EXISTS hazard_report_route_reviews
    ADD COLUMN IF NOT EXISTS routing_apply_status VARCHAR(30);

ALTER TABLE IF EXISTS hazard_report_route_reviews
    ADD COLUMN IF NOT EXISTS routing_apply_message TEXT;

ALTER TABLE IF EXISTS hazard_report_route_reviews
    ADD COLUMN IF NOT EXISTS routing_applied_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS hazard_report_route_review_segment_drafts (
    draft_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    edge_id BIGINT NOT NULL,
    walk_access VARCHAR(30),
    braille_block_state VARCHAR(30),
    audio_signal_state VARCHAR(30),
    width_state VARCHAR(30),
    surface_state VARCHAR(30),
    stairs_state VARCHAR(30),
    signal_state VARCHAR(30),
    CONSTRAINT fk_hazard_report_route_review_segment_drafts_review_id
        FOREIGN KEY (review_id)
        REFERENCES hazard_report_route_reviews (review_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_hazard_report_route_review_segment_drafts_edge_id
        FOREIGN KEY (edge_id)
        REFERENCES road_segments (edge_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_hazard_report_route_review_segment_drafts_review_edge
    ON hazard_report_route_review_segment_drafts (review_id, edge_id);

ALTER TABLE IF EXISTS hazard_report_images
    ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
